services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: blazor-movies-sqlserver
    hostname: sqlserver
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "${ACCEPT_EULA:?err}"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD:?err}"
      MSSQL_PID: "${MSSQL_PID:-Developer}"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
    driver: local